urls.py
from django.conf.urls.defaults import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
  url(r'^admin/', include(admin.site.urls)),
)

urlpatterns += patterns('events.views',
  url(r'^$', 'index'),
  url(r'^login/$', 'login'),
  url(r'^logout/$', 'logout'),
  url(r'^login-error/$', 'login_error'),
  url(r'^event/add/$', 'add_event'),
  url(r'^event/(?P<event_id>\d+)/edit/$', 'edit_event'),
  url(r'^event/(?P<event_id>\d+)/delete/$', 'delete_event'),
  url(r'^event/(?P<event_id>\d+)/state/$', 'event_state'),
  url(r'^event/(?P<event_id>\d+)/poll/$', 'event_poll'),
  url(r'^event/(?P<event_id>\d+)/vote/$', 'vote'),
  url(r'^event/(?P<event_id>\d+)/$', 'event'),
  url(r'^project/(?P<project_id>\d+)/edit/$', 'edit_project'),
  url(r'^project/(?P<project_id>\d+)/delete/$', 'delete_project'),
  url(r'^project/(?P<project_id>\d+)/join/$', 'join_project'),
  url(r'^project/(?P<project_id>\d+)/leave/$', 'leave_project'),
)

urlpatterns += patterns('',
  url(r'', include('social_auth.urls')),
)

urlpatterns += patterns('',
  (r'^comments/', include('django.contrib.comments.urls')),
)

events/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from social_auth.signals import pre_update
from events.googlebackend import GoogleProfileBackend
from pprint import pprint

# Models

class UserProfile(models.Model):
  # required field for django user profiles
  user = models.OneToOneField(User)
  # custom fields
  google_id = models.CharField(max_length=30, null=True)
  full_name = models.CharField(max_length=100, null=True)
  profile = models.CharField(max_length=200, null=True)
  picture = models.CharField(max_length=200, null=True)

  def __unicode__(self):
    if self.full_name:
      return u'%s' % self.full_name
    return self.user.username

class Hackathon(models.Model):
  RUNNING = 0
  VOTING = 1
  COMPLETED = 2
  title = models.CharField(max_length=100)
  description = models.TextField()
  start = models.DateTimeField(verbose_name='When')
  location = models.CharField(max_length=200, verbose_name='Where')
  creator = models.ForeignKey(User, related_name='created_events')
  state = models.IntegerField(default=0)
  voters = models.ManyToManyField(User, related_name='voted_events')
  deleted = models.BooleanField(default=False)

  def __unicode__(self):
    return u'%s' % self.title

class PollOption(models.Model):
  event = models.ForeignKey(Hackathon)
  text = models.CharField(max_length=300)
  count = models.IntegerField(default=0)

  def __unicode__(self):
    return u'%s' % self.text

class Project(models.Model):
  title = models.CharField(max_length=100)
  description = models.TextField()
  creator = models.ForeignKey(User, related_name='created_projects')
  event = models.ForeignKey(Hackathon)
  hackers = models.ManyToManyField(User, related_name='joined_projects')
  deleted = models.BooleanField(default=False)

  def __unicode__(self):
    return u'%s' % self.title

# Signals for models

def create_user_profile(sender, instance, created, **kwargs):
  if created:
    UserProfile.objects.create(user=instance)

post_save.connect(create_user_profile, sender=User)

def google_extra_values(sender, user, response, details, **kwargs):
  profile = user.get_profile()
  profile.google_id = response.get('id')
  profile.full_name = response.get('name')
  profile.picture = response.get('picture')
  profile.profile = response.get('link')
  pprint(vars(profile))
  profile.save()
  return True

pre_update.connect(google_extra_values, sender=GoogleProfileBackend)

events/views.py
from django.shortcuts import render_to_response, get_object_or_404
from django.http import HttpResponseRedirect, HttpResponse, HttpResponseNotFound, HttpResponseForbidden, HttpResponseBadRequest
from django.template import RequestContext
from django.contrib.auth import logout as auth_logout
from django.forms import ModelForm, Textarea, ChoiceField
from django.forms.widgets import RadioSelect
from django import forms
from django.db import models
from decorators import check_login
from django.core.urlresolvers import reverse
from events.models import Hackathon, Project, PollOption
from datetime import datetime
from pprint import pprint

def login(request):
  return render_to_response('login.html', {}, RequestContext(request))

def login_error(request):
  return render_to_response('login-error.html', {}, RequestContext(request))

@check_login()
def index(request):
  hackathons = Hackathon.objects.filter(deleted=False).order_by('start')
  in_future = []
  in_progress = []
  completed = []
  for hack in hackathons:
    if hack.state == Hackathon.COMPLETED:
      completed.append(hack)
    elif hack.start > datetime.now():
      in_future.append(hack)
    else:
      in_progress.append(hack)
      
  return render_to_response('index.html', {'hackathons': in_progress + in_future + completed, 'current_datetime': datetime.now()}, RequestContext(request))
 
@check_login()
def logout(request):
  auth_logout(request)
  return HttpResponseRedirect(reverse('events.views.login'))

@check_login()
def event(request, event_id):
  hack = get_object_or_404(Hackathon, pk=event_id)
  projects = hack.project_set.filter(deleted=False)
  if request.method == 'POST':
    form = ProjectForm(request.POST, label_suffix='')
    if form.is_valid():
      new_project = form.save(commit=False)
      new_project.creator = request.user
      new_project.event = hack
      new_project.save()
      return HttpResponseRedirect(reverse('events.views.event', args=[event_id]))
  else:
    form = ProjectForm(label_suffix='')
  return render_to_response('event.html', {'hack': hack, 'projects': projects, 'form': form, 'comment_form_excludes': ['name', 'url', 'email', 'honeypot']} , RequestContext(request))

@check_login()
def add_event(request):
  if request.method == 'POST':
    form = EventForm(request.POST, label_suffix='')
    if form.is_valid():
      new_event = form.save(commit=False)
      new_event.creator = request.user
      new_event.save()
      return HttpResponseRedirect(reverse('events.views.index'))
  else:
    form = EventForm(label_suffix='')
  return render_to_response('add_event.html', {'form': form},  RequestContext(request))

@check_login()
def edit_event(request, event_id):
  event = get_object_or_404(Hackathon, pk=event_id)
  if not event.creator == request.user:
    return HttpResponseForbidden('<h1>Forbidden - Only event author can perform changes</h1>')
  if request.method == 'POST':
    form = EventForm(request.POST, instance=event, label_suffix='')
    if form.is_valid():
      form.save()
      return HttpResponseRedirect(reverse('events.views.index'))
  else:
    form = EventForm(instance=event, label_suffix='')
  return render_to_response('edit_event.html', {'form': form, 'event': event},  RequestContext(request))

@check_login()
def delete_event(request, event_id):
  event = get_object_or_404(Hackathon, pk=event_id)
  if not event.creator == request.user:
    return HttpResponseForbidden('<h1>Forbidden - Only event author can perform changes</h1>')
  event.deleted = True
  event.save()
  return HttpResponseRedirect(reverse('events.views.index'))

@check_login()
def event_state(request, event_id):
  event = get_object_or_404(Hackathon, pk=event_id)
  if not event.creator == request.user:
    return HttpResponseForbidden('<h1>Forbidden - Only event author can perform changes</h1>')
  if not event.state == Hackathon.COMPLETED:
    event.state += 1
    event.save()
  return HttpResponseRedirect(reverse('events.views.index'))

@check_login()
def event_poll(request, event_id):
  event = get_object_or_404(Hackathon, pk=event_id)
  if event.state == Hackathon.VOTING:
    return render_to_response('poll.html', {'event': event},  RequestContext(request))
  elif event.state == Hackathon.COMPLETED:
    return render_to_response('poll.html', {'event': event},  RequestContext(request))
  return HttpResponseNotFound('<h1>Poll Not Found</h1>')

@check_login()
def vote(request, event_id):
  event = get_object_or_404(Hackathon, pk=event_id)
  if event.state != event.VOTING:
    return HttpResponseForbidden('<h1>Forbidden - Vote is not running</h1>')
  if request.user in event.voters.all():
    return HttpResponseForbidden('<h1>Forbidden - You already voted</h1>')
  option_id = request.POST['option']  
  if option_id == '-1':
    # new proposal
    proposal = request.POST['proposal']
    new_option = PollOption(event=event, text=proposal, count=1)
    new_option.save()
  else:
    # existing option
    option = get_object_or_404(PollOption, pk=option_id)
    print option.text
    if option.event == event:
      option.count += 1 
      option.save()
    else:
      return HttpResponseBadRequest('<h1>Bad Request - Option does not belong to poll</h1>')
  event.voters.add(request.user)
  return HttpResponseRedirect(reverse('events.views.event_poll', args=[event.id]))

@check_login()
def edit_project(request, project_id):
  project = get_object_or_404(Project, pk=project_id)
  if not project.creator == request.user:
    return HttpResponseForbidden('<h1>Forbidden - Only project author can perform changes</h1>')
  if request.method == 'POST':
    form = ProjectForm(request.POST, instance=project, label_suffix='')
    if form.is_valid():
      form.save()
      return HttpResponseRedirect(reverse('events.views.event', args=[project.event.id]))
  else:
    form = ProjectForm(instance=project, label_suffix='')
  return render_to_response('edit_project.html', {'form': form, 'project': project},  RequestContext(request))

@check_login()
def delete_project(request, project_id):
  project = get_object_or_404(Project, pk=project_id)
  if not project.creator == request.user:
    return HttpResponseForbidden('<h1>Forbidden - Only project author can perform changes</h1>')
  project.deleted = True
  project.save()
  return HttpResponseRedirect(reverse('events.views.event', args=[project.event.id]))

@check_login()
def join_project(request, project_id):
  project = get_object_or_404(Project, pk=project_id)
  if not request.user in project.hackers.all():
    project.hackers.add(request.user)
    project.save()
  return HttpResponseRedirect(reverse('events.views.event', args=[project.event.id]))

@check_login()
def leave_project(request, project_id):
  project = get_object_or_404(Project, pk=project_id)
  if request.user in project.hackers.all():
    project.hackers.remove(request.user)
    project.save()
  return HttpResponseRedirect(reverse('events.views.event', args=[project.event.id]))

# Forms
 
class EventForm(ModelForm):
  # specify the custom format and jquery ui class for the datetime field
  start = forms.DateTimeField(('%d %B %Y, %I%p',), widget=forms.DateTimeInput(attrs={'class':'datePicker', 'readonly':'true'}, format='%d %B %Y, %I%p'))
  class Meta:
    model=Hackathon
    fields = ('title', 'description', 'start', 'location')
    widgets = {
      'description': Textarea(attrs={'rows': 3}),
    }

class ProjectForm(ModelForm):
  class Meta:
    model=Project
    fields = ('title', 'description')
    widgets = {
      'description': Textarea(attrs={'rows': 3}),
    }

templates/add_event.html
{% extends "base.html" %}

{% block title %} Add Event {% endblock %}

{% block styles %} 
  {{ block.super }}
  <link href='http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/themes/smoothness/jquery-ui.css' rel='stylesheet' type='text/css'>
  <link href='{{STATIC_URL}}css/form.css' rel='stylesheet' type='text/css'>
  <link href='{{STATIC_URL}}css/jquery-ui-timepicker-addon.css' rel='stylesheet' type='text/css'>
  {% endblock %}

{% block scripts %}
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.18/jquery-ui.min.js" type="text/javascript"></script>
  <script src="{{STATIC_URL}}js/jquery-ui-timepicker-addon.js" type="text/javascript"></script>
  <script type="text/javascript">
    $(document).ready(function() {
      $(".datePicker").datetimepicker({
        dateFormat: 'd MM yy'
      , timeFormat: 'htt'
      , showMinute: false
      , ampm: true
      , separator: ', '
      , hour: 20
      });
    });
  </script>
{% endblock %}

{% block content %}
  <div id="content">
    <a href='{% url events.views.index %}'>&larr; Event list</a>
    <h3>New Event</h3>
    <form method='POST' action='{% url events.views.add_event %}'>
      {% csrf_token %}
      {{ form.as_p }}
      <input type="submit" value="Add Event" />
    </form>
  </div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>{% block title %}Title{% endblock %}</title>
    {% block styles %}
      <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
      <link href='{{STATIC_URL}}css/base.css' rel='stylesheet' type='text/css'>
      {% if user.is_authenticated %}
        <link href='{{STATIC_URL}}css/header.css' rel='stylesheet' type='text/css'>
      {% endif %}
    {% endblock %}
  </head>
  <body>
    {% if user.is_authenticated %}
      {% include 'header.html' %}
    {% endif %}
    {% block content %}{% endblock %}
    {% block scripts %}{% endblock %}
  </body>
</html>

templates/edit_event.html
{% extends "add_event.html" %}

{% block title %} Edit Event {% endblock %}

{% block content %}
  <div id="content">
    <a href='{% url events.views.index %}'>&larr; Event list</a>
    <h3>Edit Event</h3>
    <form method='POST' action='{% url events.views.edit_event event.id %}'>
      {% csrf_token %}
      {{ form.as_p }}
      <input type="submit" value="Edit Event" />
    </form>
  </div>
{% endblock %}

templates/edit_project.html
{% extends "add_event.html" %}

{% block title %} Edit Project {% endblock %}

{% block content %}
  <div id="content">
    <a href='{% url events.views.event project.event.id %}'>&larr; {{project.event.title}}</a>
    <h3>Edit Project</h3>
    <form method='POST' action='{% url events.views.edit_project project.id %}'>
      {% csrf_token %}
      {{ form.as_p }}
      <input type="submit" value="Edit Project" />
    </form>
  </div>
{% endblock %}

templates/event.html
{% extends "base.html" %}

{% block title %} {{hack.title}} {% endblock %}

{% block styles %} 
  {{ block.super }}
  <link href='{{STATIC_URL}}css/form.css' rel='stylesheet' type='text/css'>
  <link href='{{STATIC_URL}}css/index.css' rel='stylesheet' type='text/css'>
  <link href='{{STATIC_URL}}css/event.css' rel='stylesheet' type='text/css'>
{% endblock %}

{% block scripts %}
  {{ block.super }}
  <script type='text/javascript' src='https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js'></script>
  <script type='text/javascript'>
    $(document).ready(function() {
      $('.comment_title a').click(function() {
        classname = $(this).attr('for');
        $('#' + classname).slideToggle();
        return false;
      });
    });
  </script>
{% endblock %}

{% block content %}
  {% load comments %}
  {% load events_extras %}
  <div id="content">
    <a href='{% url events.views.index %}'>&larr; Event list</a>
    <div class="event">
      <h2><a href='{% url events.views.event hack.id %}'>{{hack.title}}</a></h2>
      {% if hack.state == hack.VOTING %}
        <a class='poll_link' href='{% url events.views.event_poll hack.id %}'>Vote hackathon hero &rarr;</a>
      {% endif %}
      {% if hack.state == hack.COMPLETED %}
        <a class='poll_link' href='{% url events.views.event_poll hack.id %}'>View hackathon hero results &rarr;</a>
      {% endif %}
      <div class="indent">
        <p class="description">{{hack.description|linebreaksbr|urlize}}</p>
        <table class="details">
          <tr>
            <td class='icon'><img src='{{STATIC_URL}}images/date.png'/></td>
            <td>{{hack.start.date}}</td>
          </tr>
          <tr>
            <td class='icon'><img src='{{STATIC_URL}}images/time.png'/></td>
            <td>{{hack.start.time}}</td>
          </tr>
          <tr>
            <td class='icon'><img src='{{STATIC_URL}}images/location.png'/></td>
            <td>{{hack.location}}</td>
          </tr>
        </table>
      </div>
    </div>
    <h3>Projects</h3>
    <ol>
    {% for project in projects %}
      <li>
        <h3 class='project_title'>{{project.title}}</h3>
        <div class='indent'>
          {% if project.creator == user %}
            <div class="mention controls">
              <a href='{% url events.views.edit_project project.id %}'>Edit</a>
              <a href='{% url events.views.delete_project project.id %}'>Delete</a>
            </div>
          {% else %}
            <div class='mention'>Added by {{project.creator.get_profile.full_name}}</div>
          {% endif %}
          <div class="description">{{project.description|linebreaksbr|urlize}}</div>
          <div class='participants'>
            {% for hacker in project.hackers.all %}
              <img class='avatar' alt=''{{hacker.get_profile.full_name}} title='{{hacker.get_profile.full_name}}' src='{{hacker.get_profile.picture|default_picture}}'>
            {% endfor %}
            {% if user in project.hackers.all %}
              <a href='{% url events.views.leave_project project.id %}'>Leave</a>
            {% else %}
              <a href='{% url events.views.join_project project.id %}'>Join</a>
            {% endif %}
          </div>
          {% get_comment_count for project as comment_count %}
          <div class='comment_title'><a href='#' for='comment_box_{{project.id}}'>{{comment_count}} Comment{{comment_count|pluralize}}</a></div>
          <div class='comment_box' id='comment_box_{{project.id}}'>
            {% get_comment_list for project as comments %}
            {% for comment in comments %}
              <div class='comment'>
                <img class='avatar left' src='{{comment.user.get_profile.picture|default_picture}}'>
                <div class='author'>{{comment.user.get_profile.full_name}}</div>
                <div class='comment_content'>{{comment.comment|linebreaksbr|urlize}}</div>
              </div>
            {% endfor %}
            {% get_comment_form for project as comment_form %}
            <form class='comment_form' action="{% comment_form_target %}" method="POST">
              {% csrf_token %}
              {% for field in comment_form %}
                {% if field.name not in comment_form_excludes %}
                  <p>{{field}}</p>
                {% endif %}
              {% endfor %}
              <input type="hidden" name="next" value="{% url events.views.event project.event.id %}" />
              <input type="submit" name="submit" value="Post">
            </form>
          </div>
        </li>
      {% endfor %}
      </ol>
      <h3>Quick Add Project</h3>
      <form action='{% url events.views.event hack.id %}' method='POST'>
        {% csrf_token %}
        {{form.as_p}} 
        <input type='submit' value='Add Project'/>
      </form>
    </div>
  </div>
{% endblock %}

templates/header.html
{% load events_extras %}
<div id='header'>
  <a class='logo' href='{% url events.views.index %}'><img src='{{STATIC_URL}}images/logo.png'></a>
  <span id='logout'>
    <img class='avatar' src='{{user.get_profile.picture|default_picture}}'>
    <span class="username">{{user.get_profile.full_name}}</span> | 
    <a href="/logout">Logout</a>
  </span>
</div>

templates/index.html
{% extends "base.html" %}

{% block title %} Hackr {% endblock %}

{% block styles %} 
  {{ block.super }}
  <link href='{{STATIC_URL}}css/index.css' rel='stylesheet' type='text/css'>
{% endblock %}

{% block content %}
  <div id="content">
    <a href='{% url events.views.add_event %}'>Add event</a>
    {% for hack in hackathons %}
      <div class="event">
        <h3><a href='{% url events.views.event hack.id %}'>{{hack.title}}</a></h3>
        {% if hack.state == hack.RUNNING and hack.start < current_datetime %}
          <span class="state">In Progress</span>
        {% endif %}
        {%if hack.state == hack.VOTING %}
          <span class="state">Vote running</span>
        {% endif %}
        {% if hack.state == hack.COMPLETED %}
          <span class="state completed">Completed</span>
        {% endif %}
        <div class="indent">
          {% if hack.creator == user %}
            <div class="mention controls">
              {% if hack.state == hack.RUNNING %}
                <a href='{% url events.views.event_state hack.id %}'>Start vote</a>
              {% endif %}
              {% if hack.state == hack.VOTING %}
                <a href='{% url events.views.event_state hack.id %}'>End vote</a>
              {% endif %}
              <a href='{% url events.views.edit_event hack.id %}'>Edit</a>
              <a class='delete' href='{% url events.views.delete_event hack.id %}'>Delete</a>
            </div>
          {% else %}
            <p class="description mention">
              Added by {{hack.creator.get_profile.full_name}}
            </p>
          {% endif %}
          <p class="description">{{hack.description|linebreaksbr|urlize}}</p>
          <table class="details">
            <tr>
              <td class='icon'><img src='{{STATIC_URL}}images/date.png'/></td>
              <td>{{hack.start.date}}</td>
            </tr>
            <tr>
              <td class='icon'><img src='{{STATIC_URL}}images/time.png'/></td>
              <td>{{hack.start.time}}</td>
            </tr>
            <tr>
              <td class='icon'><img src='{{STATIC_URL}}images/location.png'/></td>
              <td>{{hack.location}}</td>
            </tr>
          </table>
        </div>
      </div>
    {% endfor %}
  </div>
{% endblock %}

templates/login-error.html
{% extends "login.html" %}

{% block title %}Hackr Login Error{% endblock %}

{% block content %}
    <h3 style='margin:8px; color: #DD5525; text-align:center;'>Login Error. Try again.</h3>
    {{ block.super }}
{% endblock %}

templates/login.html
{% extends "base.html" %}

{% block title %} Hackr Login {% endblock %}

{% block content %}
  <div id='content'>
    <div class='login'>
      <div style='overflow:auto'><img src='{{STATIC_URL}}images/logo.png'></div>
      <a href="{% url socialauth_begin 'google-profile' %}">Enter using Google Account</a>
    </div>
  </div>
{% endblock %}

templates/poll.html
{% extends "base.html" %}

{% block title %} Poll for {{event.title}} {% endblock %}

{% block styles %} 
  {{ block.super }}
  <link href='{{STATIC_URL}}css/index.css' rel='stylesheet' type='text/css'>
  <link href='{{STATIC_URL}}css/form.css' rel='stylesheet' type='text/css'>
{% endblock %}

{% block content %}
  {% load events_extras %}
  <div id="content">
    <a href='{% url events.views.event event.id %}'>&larr; Back to event</a>
    <div class='vote_form'>
      {% if event.state == event.VOTING %}
        <h3>Vote form for {{event.title}}</h3>
        <form action="{% url events.views.vote event.id %}" method="POST">
          {% csrf_token %}
          {% for option in event.polloption_set.all %}
            <div class='poll_option'>
              <input type="radio" name="option" id="choice{{ forloop.counter }}" value="{{ option.id }}" />
              <label for="choice{{ forloop.counter }}">{{ option.text }}</label>
            </div>
          {% endfor %}
          <div class='poll_option'>
            <input type="radio" name="option" id="choice" value="-1" checked='checked'/>
            <label for="choice">New proposal</label>
            <input type="text" name='proposal'/>
          </div>
          {% if user in event.voters.all %}
            <input class='vote_button' type="submit" disabled="disabled" value="You already voted" />
          {% else %}
            <input class-'vote_button' type="submit" value="Vote" />
          {% endif %}
        </form>
        <div class='vote_details'>Current number of votes: {{ event.voters.all|length }}</div>
      {% endif %}
      {% if event.state == event.COMPLETED %}
        <h3>Vote results for {{event.title}}</h3>
        <table class='vote_listing'>
          {% for option in event.polloption_set.all %}
            <tr><td><ul><li><span class='vote_result'>{{option.text}}</span></li></ul></td><td>{{option.count}} sudo{{option.count|pluralize}}</td></tr>
          {% endfor %}
        </table>
        <h4>Voters</h4>
        {% for voter in event.voters.all %}
          <img class='avatar' alt='{{voter.get_profile.full_name}}' title='{{voter.get_profile.full_name}}' src='{{voter.get_profile.picture|default_picture}}'>
        {% endfor %}
      {% endif %}
    </div>
  </div>
{% endblock %}